/*
   -- TerraGator --
   
   To compile this code using RemoteXY library 4.1.4 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.16.02 or later version;
     - for iOS 1.13.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/



#include <Wire.h>           //I2C library
#define ARDUINO_I2C_ADDRESS   0x20  //Arduino I2C address
#define RP2350_I2C_ADDRESS    0x40


//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__ARDUINOBLE

#include <ArduinoBLE.h>


// RemoteXY connection settings 
#define REMOTEXY_BLUETOOTH_NAME "TerraGator"


#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t RemoteXY_CONF[] =   // 77 bytes
  { 255,3,0,0,0,70,0,19,0,0,0,0,31,2,106,200,200,84,1,1,
  2,0,5,26,125,52,52,132,15,60,60,33,2,26,31,12,18,10,69,11,
  5,8,40,10,194,30,26,102,111,114,119,97,114,100,0,114,101,118,101,114,
  115,101,0,98,114,97,107,101,0,110,101,117,116,114,97,108,0 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // input variables
  int8_t joystick_01_x; // from -100 to 100
  int8_t joystick_01_y; // from -100 to 100
  uint8_t rover_mode; // from 0 to 4

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////


// Define global variables
int8_t velocity = 0;
uint8_t mode = 0;


void requestEvent(){
  //  ISR for when Pico requests data from Uno R4
  Wire.write((uint8_t)velocity);
  Wire.write(mode);
}

void setup() 
{
  RemoteXY_Init (); 
  
  //**********<I2C Init>**********
    Wire.begin(ARDUINO_I2C_ADDRESS);
    Wire.onRequest(requestEvent);   // register ISR
  //**********</I2C Init>**********
  
}

void loop() 
{ 
  // First, run RemoteXY_Handler (required by library)
    RemoteXY_Handler ();

  // Second, read values from RemoteXY components
    velocity = RemoteXY.joystick_01_y;
    mode    = RemoteXY.rover_mode;
    // I2C requestEvent ISR will handle sending data to Pico

  // Third, delay a bit (using RemoteXY_delay)
    RemoteXY_delay(100);

}